# Generated by Django 2.1.8 on 2019-05-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190515_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, default=1, max_length=60),
            preserve_default=False,
        ),
    ]
