# Generated by Django 2.1.8 on 2019-05-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_pick_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pick_movie',
        ),
    ]
