# Generated by Django 2.1.8 on 2019-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0005_remove_user_pick_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pick_movie',
            field=models.ManyToManyField(blank=True, related_name='pick_user', to='movies.Movie'),
        ),
    ]
