# Generated by Django 2.1.8 on 2019-05-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_pick_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
