# Generated by Django 2.1.8 on 2019-05-09 01:12

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('open_date', models.CharField(max_length=8)),
                ('audience', models.IntegerField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='movies/images')),
                ('actors', models.CharField(max_length=60)),
                ('directors', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=30)),
                ('nations', models.CharField(max_length=30)),
                ('show_time', models.CharField(max_length=3)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('open_date', models.CharField(max_length=8)),
                ('audience', models.IntegerField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='movies/images')),
                ('actors', models.CharField(max_length=60)),
                ('directors', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=30)),
                ('nations', models.CharField(max_length=30)),
                ('show_time', models.CharField(max_length=3)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('rank_inten', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='movies/images')),
                ('grade', models.CharField(max_length=30)),
                ('show_time', models.CharField(max_length=3)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRankEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('rank_inten', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='movies/images')),
                ('grade', models.CharField(max_length=30)),
                ('show_time', models.CharField(max_length=3)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='movieranken',
            name='today',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Today'),
        ),
        migrations.AddField(
            model_name='movierank',
            name='today',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Today'),
        ),
    ]
