# Generated by Django 2.1.8 on 2019-05-14 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedip',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviedip',
            name='user',
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='MovieDip',
        ),
    ]
