# Generated by Django 2.1.8 on 2019-05-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(blank=True, max_length=50)),
                ('actor', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='movieen',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movieranken',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movieranken',
            name='today',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movierank',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movierank',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='movierank',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movierank',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='movierank',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movierank',
            name='today',
        ),
        migrations.AddField(
            model_name='movie',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='movierank',
            name='date',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movierank',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MovieEn',
        ),
        migrations.DeleteModel(
            name='MovieRankEn',
        ),
        migrations.DeleteModel(
            name='Today',
        ),
        migrations.AddField(
            model_name='people',
            name='movies',
            field=models.ManyToManyField(related_name='peoples', to='movies.Movie'),
        ),
    ]
